# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[2.0864e-01, 3.5300e-03, 6.8157e-01, 2.2699e-01, 9.2710e-01, 6.8887e-01,
         7.6483e-01],
        [4.5686e-01, 5.0601e-01, 1.0604e-01, 4.1996e-01, 1.4815e-01, 1.9691e-01,
         2.8025e-01],
        [8.9504e-01, 3.2642e-01, 9.4595e-01, 5.2702e-01, 3.4153e-01, 8.0188e-01,
         9.2488e-01],
        [4.4025e-03, 6.4246e-01, 1.2727e-01, 7.7131e-01, 5.5779e-02, 6.8200e-04,
         1.6900e-01],
        [9.1096e-01, 1.9379e-01, 5.8108e-01, 3.2240e-01, 6.5842e-01, 7.7851e-01,
         1.9995e-01],
        [2.3027e-01, 7.1493e-01, 4.2466e-01, 9.1932e-01, 5.9631e-01, 8.6152e-01,
         3.3421e-01],
        [5.2958e-01, 9.0835e-01, 7.3898e-01, 3.2144e-01, 6.7270e-01, 5.2563e-01,
         9.9191e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication 
result = torch.matmul(random_tensor, random_tensor_2.T)
result

tensor([[2.0028],
        [1.2162],
        [2.9175],
        [1.0400],
        [2.1270],
        [2.2596],
        [2.8310]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_A = torch.rand(7, 7)
random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(random_tensor_A, random_tensor_B.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.cuda.manual_seed(1234)
torch.manual_seed(1234)

# Check for access to GPU
# torch.cuda.is_available()

# Create two random tensors on GPU
random_a = torch.rand(2, 3)
random_b = torch.rand(2, 3)

print(random_a, random_b)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
multiplied_mat = torch.matmul(random_a, random_b.T)
multiplied_mat

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
max_val = multiplied_mat.max()
# Find min
min_val = multiplied_mat.min()

max_val, min_val

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
# Find arg max
max_index = multiplied_mat.argmax()

# Find arg min
min_index = multiplied_mat.argmin()

max_index, min_index

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [12]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_q10 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
removed_single_dimensions = random_tensor_q10.squeeze()

# Print out tensors and their shapes
random_tensor_q10, removed_single_dimensions, removed_single_dimensions.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))