# 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.6.0


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# scalar has no dimension
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
scalar.shape

torch.Size([])

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR2 = torch.tensor([[[1, 2, 3, 4],
                         [3, 6, 8, 9],
                         [2, 1, 5, 3]]])

In [18]:
TENSOR2.ndim

3

In [19]:
TENSOR2.shape

torch.Size([1, 3, 4])

### Random tensors

Why random tensors? 

Random tensors are important because the way many neural network learn, is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
# create a random tensos of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9802, 0.6557, 0.3201, 0.4186],
        [0.7018, 0.3029, 0.7715, 0.6145],
        [0.9019, 0.0368, 0.4192, 0.8783]])

In [21]:
random_tensor.ndim

2

In [22]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

size inside torch.rand() is the same as not using size

### Zeros and ones

In [23]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# create tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [27]:
# use torch.range() and get deprecated msg, use torch.arange() instead
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note:Tensor datatypes is one of the 3 big erros you'll run into with pytorch and deeplearning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what data type is the tensor, e.g. float32/float16
                               device = None, # what device is your tensor on
                               requires_grad=False) # wehtehre or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [35]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3379, 0.6615, 0.6879, 0.1976],
        [0.8825, 0.0576, 0.0236, 0.8209],
        [0.8591, 0.5542, 0.7138, 0.0016]])

In [36]:
# find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3379, 0.6615, 0.6879, 0.1976],
        [0.8825, 0.0576, 0.0236, 0.8209],
        [0.8591, 0.5542, 0.7138, 0.0016]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [37]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing mmultiplication
- Element-wise multiplication
- Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
* `(a, b) @ (c, d)` to work, b == c should be true
2. The resulting matrix has the shape of outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`
* `(a, b) @ (b, d)` -> `(a, d)`


In [42]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [45]:
tensor @ tensor

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 723 µs, sys: 945 µs, total: 1.67 ms
Wall time: 1.29 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 93 µs, sys: 23 µs, total: 116 µs
Wall time: 112 µs


tensor(14)

### One of the most common in deep learning is shape errors

In [48]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul()


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose

A transpose switches the axes or dimension of a given tensors

In [50]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [51]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [53]:
# matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [55]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# torch.mean() requires tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# find position in tensor that has min values with argmin() -> return the index position of minimum value
x.argmin()

tensor(0)

In [61]:
# find position in tensor that has max values with argmax() -> return the index position of maximum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezzing, unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [62]:
# let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# change the view
z = x.view(1, 9)
z, z.shape # changing z changes x (because it has the same memory)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked # hstack dim = 1, vstack dim = 0

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
# torch.squeeze() -> remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"new shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [68]:
x_reshaped.shape

torch.Size([1, 9])

In [69]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [70]:
x_reshaped.squeeze().shape

torch.Size([9])

In [71]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [72]:
# torch.permute() - rearrange the dimensions of a target tensor in a specified order
x_originial = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_originial.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_originial.shape}")
print(f"new shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [73]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
# Let;s index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
# lets index on middle bracket
x[0][0], x[0, 0] # both are the same thing

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [76]:
# lets index on the most inner bracket
x[0][0][0]

tensor(1)

In [77]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [78]:
# get all values of 0th and 1st dimension, but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [79]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [80]:
#Get index 0 of 0th and 1 dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [81]:
# index on x to return 9
x[0, 2, 2]

tensor(9)

In [82]:
# index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library. 
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [83]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor # array use float64, so tensor will use float64 instead of float32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
array.dtype

dtype('float64')

In [85]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [86]:
# Change value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # numpy_tensor reflects tensor default datatype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
# change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

How neural network learns in a nutshell
`start with random number -> tensor operations -> update random numbers to make them better -> do it again -> again...`

to reduce randomness in neural network in pytorch, there is a concept random seed

basically it "flavour" the randomness

In [91]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7909, 0.3209, 0.7094, 0.8946],
        [0.9044, 0.4840, 0.6516, 0.9721],
        [0.4078, 0.4975, 0.1751, 0.5545]])
tensor([[0.7703, 0.5615, 0.8687, 0.4624],
        [0.4270, 0.9478, 0.7236, 0.6272],
        [0.5616, 0.8925, 0.4635, 0.3773]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [93]:
# let's make some random but reproducible answers
# set random seed, setting random seed only work for one line of code/operation
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers

### 1. Getting a GPU

1. Easiest - Use google colab for a free gpu
2. use your own gpu- takes a little bit of setup
3. use cloud computing - gcp, aws, azure, allow to rent computers on the cloud

In [96]:
print(torch.backends.mps.is_available())

True


### 2. Check for GPU access with PyTorch

In [97]:
# check for gpu access
torch.cuda.is_available() # no access

False

In [98]:
# Setup device agnostice code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [99]:
# count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU
to do faster computations

In [101]:
# create tensors

tensor = torch.tensor([1, 2, 3])

# tensors not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [102]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the cpu

In [ ]:
# if tensor is on gpu, can't transform it to numpy
# can't show the error since I'm not using gpu atm
# tensor_on_gpu.numpy()

In [103]:
# to fix it, set it back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])