# 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [146]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.6.0


## Introduction to Tensors

### Creating tensors

In [147]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [148]:
# scalar has no dimension
scalar.ndim

0

In [149]:
# get tensor back as python int
scalar.item()

7

In [150]:
scalar.shape

torch.Size([])

In [151]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [152]:
vector.ndim

1

In [153]:
vector.shape

torch.Size([2])

In [154]:
# matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [155]:
MATRIX.ndim

2

In [156]:
MATRIX[0]

tensor([7, 8])

In [157]:
MATRIX.shape

torch.Size([2, 2])

In [158]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [159]:
TENSOR.ndim

3

In [160]:
TENSOR.shape

torch.Size([1, 3, 3])

In [161]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [162]:
TENSOR2 = torch.tensor([[[1, 2, 3, 4],
                         [3, 6, 8, 9],
                         [2, 1, 5, 3]]])

In [163]:
TENSOR2.ndim

3

In [164]:
TENSOR2.shape

torch.Size([1, 3, 4])

### Random tensors

Why random tensors? 

Random tensors are important because the way many neural network learn, is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [165]:
# create a random tensos of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4043, 0.4264, 0.9798, 0.0920],
        [0.3828, 0.5639, 0.8724, 0.5907],
        [0.5055, 0.1007, 0.0929, 0.9494]])

In [166]:
random_tensor.ndim

2

In [167]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

size inside torch.rand() is the same as not using size

### Zeros and ones

In [168]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [169]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [170]:
# create tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [171]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [172]:
# use torch.range() and get deprecated msg, use torch.arange() instead
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
# creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note:Tensor datatypes is one of the 3 big erros you'll run into with pytorch and deeplearning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [174]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what data type is the tensor, e.g. float32/float16
                               device = None, # what device is your tensor on
                               requires_grad=False) # wehtehre or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [175]:
float_32_tensor.dtype

torch.float32

In [176]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [177]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [178]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [179]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [180]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3651, 0.1588, 0.3379, 0.3525],
        [0.4601, 0.0398, 0.4406, 0.0879],
        [0.9871, 0.8071, 0.0191, 0.9154]])

In [181]:
# find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3651, 0.1588, 0.3379, 0.3525],
        [0.4601, 0.0398, 0.4406, 0.0879],
        [0.9871, 0.8071, 0.0191, 0.9154]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [182]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [183]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [184]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [185]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [186]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing mmultiplication
- Element-wise multiplication
- Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
* `(a, b) @ (c, d)` to work, b == c should be true
2. The resulting matrix has the shape of outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`
* `(a, b) @ (b, d)` -> `(a, d)`


In [187]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [188]:
torch.matmul(tensor, tensor)

tensor(14)

In [189]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [190]:
tensor @ tensor

tensor(14)

In [191]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 604 µs, sys: 568 µs, total: 1.17 ms
Wall time: 754 µs


In [192]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 102 µs, sys: 27 µs, total: 129 µs
Wall time: 114 µs


tensor(14)

### One of the most common in deep learning is shape errors

In [193]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul()


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose

A transpose switches the axes or dimension of a given tensors

In [196]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [197]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [204]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [202]:
# matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [210]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [207]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [208]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [213]:
# torch.mean() requires tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [214]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [215]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [216]:
# find position in tensor that has min values with argmin() -> return the index position of minimum value
x.argmin()

tensor(0)

In [217]:
# find position in tensor that has max values with argmax() -> return the index position of maximum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezzing, unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [218]:
# let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [235]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [226]:
# change the view
z = x.view(1, 9)
z, z.shape # changing z changes x (because it has the same memory)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [227]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [231]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked # hstack dim = 1, vstack dim = 0

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [240]:
# torch.squeeze() -> remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"new shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [237]:
x_reshaped.shape

torch.Size([1, 9])

In [238]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [239]:
x_reshaped.squeeze().shape

torch.Size([9])

In [245]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [247]:
# torch.permute() - rearrange the dimensions of a target tensor in a specified order
x_originial = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_originial.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_originial.shape}")
print(f"new shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])
