# 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.6.0


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# scalar has no dimension
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [10]:
scalar.shape

torch.Size([])

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
# matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [24]:
TENSOR2 = torch.tensor([[[1, 2, 3, 4],
                         [3, 6, 8, 9],
                         [2, 1, 5, 3]]])

In [25]:
TENSOR2.ndim

3

In [26]:
TENSOR2.shape

torch.Size([1, 3, 4])

### Random tensors

Why random tensors? 

Random tensors are important because the way many neural network learn, is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [28]:
# create a random tensos of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9457, 0.2587, 0.1184, 0.4920],
        [0.0508, 0.7404, 0.9761, 0.6050],
        [0.9479, 0.6682, 0.5326, 0.7675]])

In [29]:
random_tensor.ndim

2

In [31]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

size inside torch.rand() is the same as not using size

### Zeros and ones

In [35]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# create tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [46]:
# use torch.range() and get deprecated msg, use torch.arange() instead
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note:Tensor datatypes is one of the 3 big erros you'll run into with pytorch and deeplearning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [53]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what data type is the tensor, e.g. float32/float16
                               device = None, # what device is your tensor on
                               requires_grad=False) # wehtehre or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [55]:
float_32_tensor.dtype

torch.float32

In [56]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [64]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [65]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [66]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9681, 0.5675, 0.0707, 0.8020],
        [0.4333, 0.4415, 0.7319, 0.0226],
        [0.4184, 0.8126, 0.7209, 0.1298]])

In [67]:
# find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9681, 0.5675, 0.0707, 0.8020],
        [0.4333, 0.4415, 0.7319, 0.0226],
        [0.4184, 0.8126, 0.7209, 0.1298]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [70]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [71]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [73]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [74]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [75]:
torch.add(tensor, 10)

tensor([11, 12, 13])